/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cyber_spectrum_analyzer_sink.h)                            */
/* BINDTOOL_HEADER_FILE_HASH(0)                                                    */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cyberether/cyber_spectrum_analyzer_sink.h>

void bind_cyber_spectrum_analyzer_sink(py::module& m)
{
    using sink = gr::cyberether::cyber_spectrum_analyzer_sink;
    py::class_<sink, gr::sync_block, gr::block, gr::basic_block,
               std::shared_ptr<sink>>(m, "cyber_spectrum_analyzer_sink_c")
        .def(py::init(&sink::make),
             py::arg("fft_size")         = 1024,
             py::arg("name")             = "spectrum analyzer",
             py::arg("range_min")        = -100.0f,
             py::arg("range_max")        = 0.0f,
             py::arg("averaging")        = 1,
             py::arg("max_hold")         = false,
             py::arg("waterfall_height") = 512,
             py::arg("gui_hint")         = "");
}
