/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cyber_range.h)                                             */
/* BINDTOOL_HEADER_FILE_HASH(0)                                                    */
/***********************************************************************************/

#include <pybind11/functional.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cyberether/cyber_range.h>

void bind_cyber_range(py::module& m)
{
    using range = gr::cyberether::cyber_range;
    py::class_<range, std::shared_ptr<range>>(m, "cyber_range")
        .def(py::init(&range::make),
             py::arg("label"),
             py::arg("min"),
             py::arg("max"),
             py::arg("value"),
             py::arg("gui_hint") = "")
        // The slider callback fires on Superluminal's present thread; take the
        // GIL before entering Python.
        .def("set_callback",
             [](range& self, py::function callback) {
                 self.set_callback([callback](float value) {
                     py::gil_scoped_acquire gil;
                     callback(value);
                 });
             })
        .def("value", &range::value);
}
