/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cyber_waterfall_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fc0940c5d2152eefc6fea12010a89fd1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cyberether/cyber_waterfall_sink.h>

void bind_cyber_waterfall_sink(py::module& m)
{
    using cyber_waterfall_sink = gr::cyberether::cyber_waterfall_sink;

    py::class_<cyber_waterfall_sink, gr::sync_block, gr::block, gr::basic_block,
               std::shared_ptr<cyber_waterfall_sink>>(m, "cyber_waterfall_sink")
        .def(py::init(&cyber_waterfall_sink::make),
             py::arg("fft_size") = 1024,
             py::arg("name")     = "waterfall",
             py::arg("height")   = 512);
}
