/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cyber_lineplot_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(99dac00369c4e2a136619a8a49b85b9f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cyberether/cyber_lineplot_sink.h>
#include <jetstream/superluminal.hh>

template <typename T>
static void bind_one(py::module& m, const char* name)
{
    using sink = gr::cyberether::cyber_lineplot_sink<T>;
    py::class_<sink, gr::sync_block, gr::block, gr::basic_block,
               std::shared_ptr<sink>>(m, name)
        .def(py::init(&sink::make),
             py::arg("buffer_size") = 4096,
             py::arg("name")        = "lineplot",
             py::arg("display")     = Jetstream::Superluminal::Domain::Time);
}

void bind_cyber_lineplot_sink(py::module& m)
{
    bind_one<gr_complex>(m, "cyber_lineplot_sink_c");
    bind_one<float>     (m, "cyber_lineplot_sink_f");
}
