/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cyber_null_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6a4912c9e0c214b80d1eb7d68f640771)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cyberether/cyber_null_sink.h>
// pydoc.h is automatically generated in the build directory
#include <cyber_null_sink_pydoc.h>

void bind_cyber_null_sink(py::module& m)
{

    using cyber_null_sink    = gr::cyberether::cyber_null_sink;


    py::class_<cyber_null_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<cyber_null_sink>>(m, "cyber_null_sink", D(cyber_null_sink))

        .def(py::init(&cyber_null_sink::make),
           D(cyber_null_sink,make)
        )
        



        ;




}








