/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cyber_waterfall_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(91254039774674d2b03d04cb419ac84c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cyberether/cyber_waterfall_sink.h>
#include <jetstream/superluminal.hh>

template <typename T>
static void bind_one(py::module& m, const char* name)
{
    using sink = gr::cyberether::cyber_waterfall_sink<T>;
    py::class_<sink, gr::sync_block, gr::block, gr::basic_block,
               std::shared_ptr<sink>>(m, name)
        .def(py::init(&sink::make),
             py::arg("fft_size")  = 1024,
             py::arg("name")      = "waterfall",
             py::arg("height")    = 512,
             py::arg("operation") = Jetstream::Superluminal::Operation::Amplitude,
             py::arg("display")   = Jetstream::Superluminal::Domain::Frequency);
}

void bind_cyber_waterfall_sink(py::module& m)
{
    bind_one<gr_complex>(m, "cyber_waterfall_sink_c");
    bind_one<float>     (m, "cyber_waterfall_sink_f");
}
