/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cyber_lineplot_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(81299383f3edd0ab90ffccd7255fe6f9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cyberether/cyber_lineplot_sink.h>
// pydoc.h is automatically generated in the build directory
#include <cyber_lineplot_sink_pydoc.h>

void bind_cyber_lineplot_sink(py::module& m)
{

    using cyber_lineplot_sink    = gr::cyberether::cyber_lineplot_sink;


    py::class_<cyber_lineplot_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<cyber_lineplot_sink>>(m, "cyber_lineplot_sink", D(cyber_lineplot_sink))

        .def(py::init(&cyber_lineplot_sink::make),
           py::arg("buffer_size") = 4096,
           py::arg("name") = "lineplot",
           D(cyber_lineplot_sink,make)
        )

        ;
}
